# Generated by Django 3.0.9 on 2020-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200816_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appnum',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
