# Generated by Django 3.0.9 on 2020-08-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200821_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appstatus',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('On Design', 'On Design'), ('Site visited', 'Site visited'), ('Installed', 'Installed')], max_length=200, null=True),
        ),
    ]
