# Generated by Django 3.0.9 on 2020-09-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_order_agreebtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreewayleave',
            field=models.CharField(choices=[('YES I AGREE', 'YES I AGREE'), ('NO I DO NOT AGREE', 'NO I DO NOT AGREE')], max_length=200, null=True),
        ),
    ]
