# Generated by Django 3.0.9 on 2020-09-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_order_agreewayleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='supplyagreement',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='wayleaves',
        ),
    ]
