# Generated by Django 3.0.9 on 2020-09-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200902_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
    ]
