# Generated by Django 3.0.9 on 2020-09-22 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200902_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rsp',
        ),
    ]
