# Generated by Django 3.0.9 on 2020-09-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200923_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mocnum',
        ),
        migrations.AlterField(
            model_name='order',
            name='appstatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
