# Generated by Django 3.0.9 on 2020-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200923_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appcontrol',
            field=models.CharField(blank=True, default='busdevclerk', max_length=200, null=True),
        ),
    ]
