# Generated by Django 3.0.9 on 2020-09-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_order_appcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appstatus',
            field=models.CharField(blank=True, default='Under Review', max_length=200, null=True),
        ),
    ]
