# Generated by Django 3.0.9 on 2020-09-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200924_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installnote',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
