# Generated by Django 3.0.9 on 2020-09-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200924_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qoutation',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
