# Generated by Django 3.0.9 on 2020-09-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200924_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qoute',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
