# Generated by Django 3.0.9 on 2020-09-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_customer_qoute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qoute',
        ),
    ]
