# Generated by Django 3.0.9 on 2020-09-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_customer_qoute'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proposal',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
