# Generated by Django 3.0.9 on 2020-09-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_order_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='maplatlon',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='proposal',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
