# Generated by Django 3.0.9 on 2020-09-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200925_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
