# Generated by Django 3.0.9 on 2020-09-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200927_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='appliances',
        ),
        migrations.DeleteModel(
            name='Appliance',
        ),
    ]
