# Generated by Django 3.0.3 on 2020-09-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200930_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='constituency',
            field=models.CharField(choices=[('Changamwe', 'Changamwe'), ('Jomvu', 'Jomvu'), ('Kisauni', 'Kisauni'), ('Nyali', 'Nyali'), ('Likoni', 'Likoni'), ('Mvita', 'Mvita'), ('Msambweni', 'Msambweni'), ('Lunga Lunga', 'Lunga Lunga'), ('Matuga', 'Matuga'), ('Kinango', 'Kinango'), ('Kilifi North', 'Kilifi North'), ('Kilifi South', 'Kilifi South'), ('Kaloleni', 'Kaloleni'), ('Rabai', 'Rabai'), ('Ganze', 'Ganze'), ('Malindi', 'Malindi'), ('Magarini', 'Magarini'), ('Garsen', 'Garsen'), ('Galole', 'Galole'), ('Bura', 'Bura'), ('Lamu East', 'Lamu East'), ('Lamu West', 'Lamu West'), ('Taveta', 'Taveta'), ('Wundanyi', 'Wundanyi'), ('Mwatate', 'Mwatate'), ('Vo', 'Vo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Tana River', 'Tana River'), ('Taita Taveta', 'Taita Taveta')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ward',
            field=models.CharField(choices=[('CHAANI', 'CHAANI'), ('MIRITINI', 'MIRITINI'), ('AIRPORT', 'AIRPORT'), ('PORT REITZ', 'PORT REITZ'), ('KIPEVU', 'KIPEVU'), ('JOMVU KUU', 'JOMVU KUU'), ('MAGONGO', 'MAGONGO'), ('MIKINDANI', 'MIKINDANI'), ('SHANZU', 'SHANZU'), ('MWAKIRUNGE', 'MWAKIRUNGE'), ('MJAMBERE', 'MJAMBERE'), ('MAGOGONI', 'MAGOGONI'), ('JUNDA', 'JUNDA'), ('MTOPANGA', 'MTOPANGA'), ('BAMBURI', 'BAMBURI'), ('MKOMANI', 'MKOMANI'), ('KONGOWEA', 'KONGOWEA'), ('KADZANDANI', 'KADZANDANI'), ("ZIWA LA NG'OMBE", "ZIWA LA NG'OMBE"), ('FRERE TOWN', 'FRERE TOWN'), ('MTONGWE', 'MTONGWE'), ('TIMBWANI', 'TIMBWANI'), ('BOFU', 'BOFU'), ('LIKONI', 'LIKONI'), ('SHIKA ADABU', 'SHIKA ADABU'), ('MJI WA KALE/ MAKADARA', 'MJI WA KALE/ MAKADARA'), ('TUDOR', 'TUDOR'), ('TONONOKA', 'TONONOKA'), ('SHIMANZI/ GANJONI', 'SHIMANZI/ GANJONI'), ('MAJENGO', 'MAJENGO'), ('RAMISI', 'RAMISI'), ('GOMBATO BONGWE', 'GOMBATO BONGWE'), ('UKUNDA', 'UKUNDA'), ('KINONDO', 'KINONDO'), ('PONGWE KIDIMU/KIGWEDE', 'PONGWE KIDIMU/KIGWEDE'), ('VANGA', 'VANGA'), ('MWERENI', 'MWERENI'), ('DZOMBO', 'DZOMBO'), ('KUBO SOUTH', 'KUBO SOUTH'), ('MKONGANI', 'MKONGANI'), ('TSIMBA GOLINI', 'TSIMBA GOLINI'), ('TIWI', 'TIWI'), ('WAA', 'WAA'), ('MACKINON ROAD', 'MACKINON ROAD'), ('NDAVAYA', 'NDAVAYA'), ('PUMA', 'PUMA'), ('KINANGO', 'KINANGO'), ('KASEMENI', 'KASEMENI'), ('MWAVUMBO', 'MWAVUMBO'), ('CHENGONI/SAMBURU', 'CHENGONI/SAMBURU'), ('MATSANGONI', 'MATSANGONI'), ('MNARANI', 'MNARANI'), ('SOKONI', 'SOKONI'), ('TEZO', 'TEZO'), ('KIBARANI', 'KIBARANI'), ('WATAMU', 'WATAMU'), ('DABASO', 'DABASO'), ('JUNJU', 'JUNJU'), ('SHIMO LA TEWA', 'SHIMO LA TEWA'), ('MTEPENI', 'MTEPENI'), ('CHASIMBA', 'CHASIMBA'), ('MWARAKAYA', 'MWARAKAYA'), ('KAYAFUNGO', 'KAYAFUNGO'), ('MARIAKANI', 'MARIAKANI'), ('MWANAMWINGA', 'MWANAMWINGA'), ('KALOLENI', 'KALOLENI'), ('JIBANA/KAMBE/RIBE', 'JIBANA/KAMBE/RIBE'), ('MAZERASRABAI/KISURUTINI', 'MAZERASRABAI/KISURUTINI'), ('MWAWESA', 'MWAWESA'), ('RURUMA', 'RURUMA'), ('SOKOKE', 'SOKOKE'), ('BAMBA', 'BAMBA'), ('JARIBUNI', 'JARIBUNI'), ('DUNGICHA/ GANZE', 'DUNGICHA/ GANZE'), ('JILORE', 'JILORE'), ('GANDA', 'GANDA'), ('KAKUYUNI', 'KAKUYUNI'), ('SHELLA', 'SHELLA'), ('MALINDI TOWN', 'MALINDI TOWN'), ('ADU', 'ADU'), ('MARAFA', 'MARAFA'), ('SABAKI', 'SABAKI'), ('MAGARINI', 'MAGARINI'), ('GONGONI', 'GONGONI'), ('GARASHI', 'GARASHI'), ('GARSEN NORTH', 'GARSEN NORTH'), ('GARSEN WEST', 'GARSEN WEST'), ('GARSEN CENTRAL', 'GARSEN CENTRAL'), ('KIPINI EAST', 'KIPINI EAST'), ('GARSEN SOUTH', 'GARSEN SOUTH'), ('KIPINI WEST', 'KIPINI WEST'), ('CHEWANI', 'CHEWANI'), ('KINAKOMBA', 'KINAKOMBA'), ('MAKINDUNI', 'MAKINDUNI'), ('WAYU', 'WAYU'), ('BANGALE', 'BANGALE'), ('CHEWELE', 'CHEWELE'), ('HIRIMAN', 'HIRIMAN'), ('MADOGO', 'MADOGO'), ('SALA', 'SALA'), ('KIUNGA', 'KIUNGA'), ('BASUBA', 'BASUBA'), ('FAZA', 'FAZA'), ('MKOMANI', 'MKOMANI'), ('SHELLA', 'SHELLA'), ('WITU', 'WITU'), ('HINDI', 'HINDI'), ('HONGWE', 'HONGWE'), ('BAHARI', 'BAHARI'), ('MKUNUMBI', 'MKUNUMBI'), ('MATA', 'MATA'), ('MAHOO', 'MAHOO'), ('MBOGHONI', 'MBOGHONI'), ('CHALA', 'CHALA'), ('BOMANI', 'BOMANI'), ('MWANDA/MGANGE', 'MWANDA/MGANGE'), ('KISHUSHE/WUMINGU', 'KISHUSHE/WUMINGU'), ('WERUGHA', 'WERUGHA'), ('WUNDANYI/MBALE', 'WUNDANYI/MBALE'), ('CHAWIA', 'CHAWIA'), ('BURA', 'BURA'), ('WUSI/KISHAMBA', 'WUSI/KISHAMBA'), ('RONGE', 'RONGE'), ('MWATATE', 'MWATATE'), ('NGOLIA', 'NGOLIA'), ('KASIGAU', 'KASIGAU'), ('MARUNGU', 'MARUNGU'), ('SAGALA', 'SAGALA'), ('MBOLOLO', 'MBOLOLO'), ('KALOLEN', 'KALOLEN')], max_length=200, null=True),
        ),
    ]
